### ISSUE TITLE
NameError: name 'interpolate_resample' is not defined

### ISSUE THREAD

**Issue by hilinxinhui** [wang-fujin/Battery-dataset-preprocessing-code-library#1]
HI, I encountered an issue while running the project. Below is the traceback error message:

```Shell
Traceback (most recent call last):
  File "XJTUBatteryClass.py", line 8, in <module>
    class Battery:
  File "XJTUBatteryClass.py", line 121, in Battery
    @interpolate_resample(resample=False, num_points=128)
NameError: name 'interpolate_resample' is not defined
```

It seems that the function `interpolate_resample` is not defined or imported in the script `XJTUBatteryClass.py`. Could you please provide guidance on how to resolve this issue? Thanks in advance for your help!

**Comment by wang-fujin** [comment]
I forgot to provide this function before, and now it has been updated in `XJTUBatteryClass.py`

**Comment by hilinxinhui** [comment]
> I forgot to provide this function before, and now it has been updated in `XJTUBatteryClass.py`

Thank you for the quick update! I appreciate your prompt response and assistance.
