### ISSUE TITLE
大佬 有论文吗？

### ISSUE THREAD

**Issue by flag2fish** [wang-fujin/Battery-dataset-preprocessing-code-library#2]
可以发一下吗？我看官网上没有完整版本的，需要花钱

**Comment by wang-fujin** [comment]
[Physics-informed neural network for lithium-ion battery degradation stable modeling and prognosis.pdf](https://github.com/user-attachments/files/16578628/Physics-informed.neural.network.for.lithium-ion.battery.degradation.stable.modeling.and.prognosis.pdf)

**Comment by wang-fujin** [comment]
不知道这样行不行？如果不行的话你留下邮箱，我用邮件发你

**Comment by flag2fish** [comment]
可以 多谢了
