### ISSUE TITLE
大佬有后续处理这些数据集的代码吗

### ISSUE THREAD

**Issue by yueshangmotian** [wang-fujin/Battery-dataset-preprocessing-code-library#4]
大佬这些读取数据集的代码非常有帮助，请问有后续处理这些数据集的代码吗。

**Comment by wang-fujin** [comment]
后续的代码就根据每个人的需求来写了，根据自己提的方法以及想怎么处理数据，每个人的需求就不一样了

**Comment by yueshangmotian** [comment]
大佬您好，感谢您百忙之中的回复，我是一名开学研一的研究生，目前刚开始入门电池状态估计这一研究领域，但苦于开源的电池数据集数据处理的代码很少，最近在拜读您的《Physics-informed neural network for lithium-ion battery degradation stable modeling and prognosis》这一篇论文，感到论文撰写的十分精妙，想要进一步的学习。所以如果您方便的话，我想请问是否能分享一下您在论文中后续处理数据的代码，仅做学习使用，如果可以的话，我会非常感激，此外，如果将来在研究过程中有幸能够有成果，我也一定会在相关出版物中引用您的工作，以表达尊重和感谢。我的邮箱是987299808@qq.com
