### ISSUE TITLE
同济大学数据集无法访问

### ISSUE THREAD

**Issue by Wenwen555** [wang-fujin/Battery-dataset-preprocessing-code-library#5]
您好,请问您是否存有同济大学的数据集? 他们的网站似乎需要通过本校的校园网才可登录, 我无法访问.
若是愿意分享, 十分感谢~

**Comment by wang-fujin** [comment]
我试了一下链接，可以访问的。他们的数据集存放在Zenodo上面，不在他们学校，也不需要校园网
![4B8AF7E1](https://github.com/user-attachments/assets/c7e0c05e-c98d-4deb-9b3e-eb444b6e665e)
